apiVersion: v1
kind: Pod
metadata:
  name: two-pods
spec:
  containers
  - name: busybox1
    image: busybox:1.31
    command:
    - sleep
    - 3600
  - name: busybox2
    image: busybox:1.31
    commad: 
    - sleep
    - 3600
    volumeMounts:
    - name:
      mountPath: /foo/bar
  volumes:
  - name:
    emptyDir: {}
cat /etc/passwd | cut -f 1 -d ':' > /etc/foo/passwd 
// first colume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:
spec:
  accessModes:
    - ReadWriteMany
  storageClass: test
  hostPath:
    path:
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeVClaim
metadata:
  name:
spec:
  resoures:
    requests:
      storage:
  accessModes:
    - ReadWriteMany
  storageClass: test
---
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name: busybox
    image: busybox:1.31
    command:
    - /bin/sh
    - -c
    - sleep 3600
    volumeMounts:
    - name:
      mountPath:
  volumes:
  - name:
    persistentVolumeClaim:
      claimName:
kubectl exec -it busybox2 -- ls /etc/passwd
---
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name:
    image:
    command:
    - /bin/sh
    - -c
    - sleep 3600
kubectl cp busybox:/etc/passwd ./passwd
cat passwd
