kubectl create namespace mynamespace
kubectl run nginx --image=nginx --restart=Never --dry-run -o yaml > nginx.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: mynamespace
spec:
  containers:
  - name: nginx
    image: nginx:1.13.12
    ports:
    - containerPort: 80
---
kubectl run busybox --image=busybox --restart=Never --dry-run -o yaml --command -- env > busybox.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    commands: ['env']
---
kubectl create namespace mynamespace --dry-run -o yaml
---
kubect; create quota my --hard=cpu=1,memory=2gGi,pods=2 -o yaml --dry-run
apiVersion: v1 
kind: ResourcesQuota
metadata:
  name: test
rules:
  hard:
    requests:
      cpu: 1G
      pods: "2"
      memeory: 2Gi
---
kubectl set image pod/nginx nginx=image:1.7.1
kubectl scale deploy/nginx --replicas=3
---
kubectl get pods -o wide
kubectl run busybox --image=busybox --rm --it --restart=Never --command -- wget -O- ip:80
---
kubectl get pod/nginx -o yaml
---
kubectl get pods -o wide
---
kubectl exec -it pod/nginx --command -- /bin/sh
---
kubectl run busybox --image=busybox --restart=Never -- echo 'hello wolrd'
command: ['echo', 'hello world']
---

