kubectl create cm config --from-literal=foo=lala --from-literal=foo2=lolo
---
kubectl describe cm/config
---
kubectl create config --from-env-file=*.env
---
kubectl create cm config --from-file=key=*.txt
---
kubectl create cm options -from-literal=var5=val5
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name:
        valueFrom:
          configMapKeyRef:
            name:
            key:
    envFrom:
    - configMapRef:
        name:
---
kubectl create cm cmvolume --from--literal=var8=val8 --from-literal=var9=val9
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name:
      mountPath:
  volumes:
    - name:
      configMap:
        name:
---
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  securityContext:
    runAsUser: 100
  containers:
  - name:
    image:
    securityContext:
      capacities:
        add: ["NET_ADMIN"]
---
kubectl run nginx --image=nginx --restart=Never --requests='cpu=100m,memory=256Mi' --limits='cpu=200m,memory=512Mi'
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name:
  resources:
    requests:
      cpu:
    limits:
      memory:
---
kubectl create secret generic mysecret2 --from-literal=password=mypass
---
kubectl create secret generic mysecret3 --from-literal=passwd=mypass
---
kubectl get secret secret2 -o yaml
---
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - name:
    volumeMounts:
    - name: name
      mountPath
  volumes:
  - name:
    secretName:
---
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  containers:
  - volumeMounts:
    - mountPath:
      name:
    env:
    - name:
      valueFrom:
        secretKeyRef:
          - name:
            key:
---
kubectl create sa all --all-namespaces
---
kubectl create sa mysa -n default
---
kubectl run busybox --image=busybox --restart=Never --serviceaccount=myuser
apiVersion: v1
kind: Pod
metadata:
  name:
spec:
  serviceAccountName: myuser
  containers:
  - name:
    image: 
   
