apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox-auto
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: busybox-rs
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
