apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test
provisioner:
parameters:
mountOptions:
  - debug
reclaimPolicy: recycle
allowVolumeExpansion: true
volumeBindingMode:
  - Immediate
  - WaitForFirstConsumer
