apiVersion: v1
kind: LimitRange
metadata:
  name:
  namespace:
spec:
  limits:
  - type: PersistentVolumeClaim/Pod/Containers
    max:
      cpu:
      memory:
      storage:
    min:
  limitrequestRatio:
    - ï
