apiVersion: v1
kind: PersistentVolume
metadata:
  name: datastore
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs: 
    path: /root/k8s/pv
    server: 172.21.16.5
