apiVersion: v1
kind: PersistentVolume
metadata:
  name: datastore
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs: 
    path: /data/k8s-nfs/database
    server: 192.168.56.11
