apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liuchen-sa-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: liuchen-sa
    namespace: default
roleRef:
  kind: Role
  name: liuchen-sa-role
  apiGroup: rbac.authorization.k8s.io
