apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liuchen-role
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
