apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liuchen-rolebinding
  namespace: default
subjects:
  - kind: User
    name: liuchen
    apiGroup: ""
roleRef:
  kind: Role
  name: liuchen-role
  apiGroup: ""

