apiVersion: v1
kind: PersistentVolume
metadata:
  name: store
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backend
  nfs: 
    path: /root/k8s/store
    server: 172.21.16.5
